### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by umbardacil** [Raul6469/zenhub-discord#2]
Hello, I would like to use and contribute to the bot. But I don't see how to use it. Would it be possible to add some installation steps or explanation ? (like where the discord or zenhub token must be put and how (probably .env file))

**Comment by Raul6469** [comment]
Hi @jordankevi ! I just pushed deploy instructions in the README, hopefully it contains all necessary information for anyone to deploy the app quickly. If there is something you want to change or add, feel free to open a PR! This app is quite old now, I did it a few years ago and haven't used it since then, so I don't know if it still works
